(()=>{'use strict';
const E=TrafficAgents,$=id=>document.getElementById(id),keys=Object.keys(E.base).filter(k=>!['scenario'].includes(k));let selected='collision',result=null,applied=null,dirty=false,events=[],ack=new Set(),audience='operator';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function log(text){events.unshift({time:new Date().toLocaleTimeString('en-GB',{hour12:false}),text});events=events.slice(0,40);$('log').innerHTML=events.map(e=>'<li><time>'+esc(e.time)+'</time>'+esc(e.text)+'</li>').join('');}
function fields(){const s={scenario:E.scenarios[selected].name};for(const k of keys){const el=$(k);s[k]=el.type==='checkbox'?el.checked:k==='event'?el.value:el.value.trim()===''?NaN:Number(el.value);}return E.validate(s);}
function loadScenario(key){selected=key;const s=E.scenarios[key];for(const k of keys)if(typeof s.input[k]==='boolean')$(k).checked=s.input[k];else $(k).value=s.input[k];$('scenario-description').textContent=s.description;document.querySelectorAll('.scenario').forEach(b=>{b.classList.toggle('selected',b.dataset.key===key);b.setAttribute('aria-pressed',b.dataset.key===key?'true':'false');});analyze();}
function analyze(){try{const candidate=E.analyze(fields());result=candidate;applied=null;dirty=false;ack=new Set();$('reviewed').checked=false;$('stale').hidden=true;$('error').textContent='';$('minute').max=result.input.horizon;$('minute').value=result.input.horizon;render();log(result.input.scenario+': analysis complete. '+result.actions.filter(a=>a.status==='blocked').length+' action(s) blocked.');}catch(e){$('error').textContent=e.message;markDirty();}}
function markDirty(){dirty=true;$('stale').hidden=false;$('reviewed').checked=false;$('apply').disabled=true;$('export').disabled=true;document.querySelectorAll('.ack').forEach(b=>b.disabled=true);$('apply-status').textContent='Inputs changed. Analyze again before applying a plan.';}
function render(){const p=result.perception,b=result.baseline;const blocked=result.actions.filter(a=>a.status==='blocked').length;$('metrics').innerHTML='<div class="metric incident"><small>Fused incident assessment</small><strong>'+esc(p.label)+'</strong><span>Evidence '+p.score+'/100 · heuristic score</span></div><div class="metric"><small>Baseline spillover</small><strong style="color:'+(b.spillover?'var(--orange)':'var(--green)')+'">'+(b.spillover?'Projected':'Not projected')+'</strong><span>Within '+result.input.horizon+' simulated minutes</span></div><div class="metric"><small>Plan validation</small><strong>'+result.actions.filter(a=>a.status==='approved').length+' / '+result.actions.length+' passed</strong><span>'+blocked+' blocked · illustrative policy</span></div>';
 $('agents').replaceChildren(...result.trace.map((t,i)=>{const button=document.createElement('button');button.className='agent'+(i===3?' selected':'');button.innerHTML='<span class="icon">AGENT 0'+(i+1)+'</span><b>'+t.agent+'</b><small>Completed</small>';button.onclick=()=>{document.querySelectorAll('.agent').forEach(a=>a.classList.remove('selected'));button.classList.add('selected');$('agent-details').textContent=t.text;};return button;}));$('agent-details').textContent=result.trace[3].text;
 $('plan').innerHTML=result.actions.map(a=>'<article class="plan-item '+a.status+'"><div class="plan-title"><span>'+esc(a.title)+'</span><span class="badge '+a.status+'">'+(a.status==='approved'?'Passed':'Blocked')+'</span></div><p>'+esc(a.reason)+'</p><details'+(a.status==='blocked'?' open':'')+'><summary>View '+a.checks.length+' validation check'+(a.checks.length>1?'s':'')+'</summary><ul class="checks">'+a.checks.map(c=>'<li><strong class="'+(c.pass?'pass':'fail')+'">'+(c.pass?'PASS':'FAIL')+' · '+esc(c.name)+'</strong><br>'+esc(c.detail)+'</li>').join('')+'</ul></details></article>').join('');
 $('export').disabled=false;$('apply-status').textContent='Awaiting operator review. Only passed actions can be simulated.';syncApply();corridor();impact();responders();message();}
function syncApply(){$('apply').disabled=dirty||!!applied||!$('reviewed').checked||!result.actions.some(a=>a.status==='approved');}
function corridor(){if(!result)return;const t=Number($('minute').value),sim=applied?applied.after:result.baseline,frame=sim.timeline[t],s=result.input;const cleared=sim.clearanceMinutes!==null&&t>=sim.clearanceMinutes;const blocked=cleared?0:s.blocked;const xs=[130,405,680];let svg='<svg viewBox="0 0 820 195" role="img" aria-label="Corridor at minute '+t+'. Queues: '+frame.queues.join(', ')+' vehicles."><defs><marker id="arrow" markerWidth="7" markerHeight="7" refX="5" refY="3" orient="auto"><path d="M0 0L6 3L0 6" fill="#7395b6"/></marker></defs>';
svg+='<path d="M35 77H765" stroke="#2c435b" stroke-width="32"/><path d="M35 77H760" stroke="#7890a8" stroke-width="1" stroke-dasharray="8 9"/>';
for(let i=0;i<2;i++)svg+='<path d="M'+(xs[i]+83)+' 77H'+(xs[i+1]-82)+'" stroke="#7a99b9" stroke-width="2" marker-end="url(#arrow)"/>';
xs.forEach((x,i)=>{const fill=i===1&&blocked?'#ff8694':frame.queues[i]>=sim.storage[i]*.85?'#ffb56c':'#5bdfb5';svg+='<rect x="'+(x-71)+'" y="45" width="142" height="66" rx="8" fill="#152c3d" stroke="'+fill+'" stroke-width="2"/><text x="'+x+'" y="30" fill="#edf3fc" text-anchor="middle" font-size="14" font-weight="600">J'+(i+1)+' · '+['West Gate','Central','East Gate'][i]+'</text><text x="'+x+'" y="74" fill="'+fill+'" text-anchor="middle" font-size="23" font-weight="700">'+Math.round(frame.queues[i])+'</text><text x="'+x+'" y="95" fill="#a9bfd2" text-anchor="middle" font-size="10">QUEUED VEHICLES</text><rect x="'+(x-70)+'" y="124" width="140" height="5" rx="2" fill="#2d4258"/><rect x="'+(x-70)+'" y="124" width="'+Math.max(0,Math.min(140,frame.queues[i]/sim.storage[i]*140))+'" height="5" rx="2" fill="'+fill+'"/><text x="'+x+'" y="151" fill="#9fb7cd" text-anchor="middle" font-size="11">Storage '+sim.storage[i]+' vehicles</text>';});svg+='<text x="405" y="182" text-anchor="middle" fill="'+(blocked?'#ff8694':'#9fb7cd')+'" font-size="12">J2: '+(blocked?blocked+' of '+s.lanes+' lanes obstructed':cleared?'obstruction cleared by simulated response':'all lanes available')+'</text></svg>';$('corridor').innerHTML=svg;$('minute-label').textContent='+'+t+' min';$('corridor-mode').textContent=applied?'Approved plan / simulation':'Baseline / no intervention';}
function impact(){const b=result.baseline,a=applied?.after;const all=[...b.timeline,...(a?.timeline||[])],max=Math.max(50,...all.map(t=>t.total));const x=m=>35+m/result.input.horizon*395,y=v=>151-v/max*126;const path=data=>data.map((t,i)=>(i?'L':'M')+x(t.minute).toFixed(1)+' '+y(t.total).toFixed(1)).join(' ');let svg='<svg class="chart" viewBox="0 0 460 187" role="img" aria-label="Queued vehicles over time, baseline'+(a?' and approved intervention':'')+'">';for(let i=0;i<=3;i++){const v=max*i/3;svg+='<line x1="35" y1="'+y(v)+'" x2="430" y2="'+y(v)+'" stroke="#304357"/><text x="28" y="'+(y(v)+4)+'" fill="#9cb2c9" text-anchor="end" font-size="10">'+Math.round(v)+'</text>';}
svg+='<text x="35" y="13" fill="#9cb2c9" font-size="10">Total queued vehicles</text><path d="'+path(b.timeline)+'" stroke="#ffb56c" stroke-width="2.5" fill="none"/>'+(a?'<path d="'+path(a.timeline)+'" stroke="#5bdfb5" stroke-width="2.5" fill="none"/>':'')+'<text x="35" y="177" fill="#9cb2c9" font-size="10">Now</text><text x="430" y="177" fill="#9cb2c9" text-anchor="end" font-size="10">+'+result.input.horizon+' minutes</text></svg>';$('impact-chart').innerHTML=svg;
const fmt=(v,after)=>v.toLocaleString()+(after!==undefined?' → '+after.toLocaleString():'');$('comparison').innerHTML='<div class="compare-cell"><span>Waiting vehicle-minutes</span><b>'+fmt(b.waitVehicleMinutes,a?.waitVehicleMinutes)+'</b><span>Idling proxy, not measured emissions</span></div><div class="compare-cell"><span>Outside-corridor backlog</span><b>'+fmt(b.upstreamBacklog,a?.upstreamBacklog)+'</b><span>Vehicles unable to enter J1</span></div><div class="compare-cell"><span>Vehicles reaching corridor exit</span><b>'+fmt(b.throughput,a?.throughput)+'</b><span>Cumulative over this horizon</span></div><div class="compare-cell"><span>Obstruction clearance assumption</span><b>'+(a?.clearanceMinutes?a.clearanceMinutes+' min':'—')+'</b><span>Not a measured responder ETA</span></div>';
if(a){const change=b.waitVehicleMinutes-a.waitVehicleMinutes;const pct=b.waitVehicleMinutes?Math.abs(change)/b.waitVehicleMinutes*100:0;$('impact-note').textContent=(change>0?'Modeled in-corridor waiting decreases by ':change<0?'Modeled in-corridor waiting increases by ':'No change in modeled in-corridor waiting. ')+(change!==0?pct.toFixed(1)+'%. ':'')+'Compare the upstream backlog too; corridor waiting alone does not capture all delay. Outcomes follow demo assumptions.';}else $('impact-note').textContent='Apply a reviewed plan to compare simulated outcomes. Improvements are not guaranteed.';}
function responders(){$('responders').replaceChildren(...result.tasks.map((t,i)=>{const div=document.createElement('div');div.className='task';div.innerHTML='<b>'+esc(t.team)+'</b><p>'+esc(t.task)+'</p><div class="task-footer"><span>'+esc(ack.has(i)?'Acknowledged in simulation':t.status)+'</span></div>';if(t.status==='Simulated assignment ready'){const b=document.createElement('button');b.className='btn ack';b.textContent=ack.has(i)?'Acknowledged':'Simulate acknowledgement';b.disabled=!applied||dirty||ack.has(i);b.onclick=()=>{if(!applied||dirty)return;ack.add(i);log(t.team+': acknowledged simulated task. No external message sent.');responders();};div.querySelector('.task-footer').append(b);}return div;}));}
function message(){$('operator-tab').setAttribute('aria-selected',String(audience==='operator'));$('public-tab').setAttribute('aria-selected',String(audience==='public'));$('message').textContent=result.explanation[audience];$('message').setAttribute('aria-labelledby',audience+'-tab');}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
Object.entries(E.scenarios).forEach(([key,s])=>{const b=document.createElement('button');b.className='scenario';b.textContent=s.name;b.dataset.key=key;b.onclick=()=>loadScenario(key);$('scenarios').append(b);});
$('inputs').addEventListener('input',markDirty);$('inputs').addEventListener('change',markDirty);$('inputs').addEventListener('submit',e=>{e.preventDefault();analyze();});$('reviewed').addEventListener('change',syncApply);$('minute').addEventListener('input',corridor);
$('apply').onclick=()=>{if(dirty||!$('reviewed').checked||applied)return;applied=E.apply(result);syncApply();$('apply-status').textContent=applied.applied.length+' approved actions simulated. '+applied.blocked.length+' blocked actions excluded.';log('Applied approved plan in simulation: '+applied.applied.join(', ')+'.');corridor();impact();responders();};
$('operator-tab').onclick=()=>{audience='operator';message();};$('public-tab').onclick=()=>{audience='public';message();};$('reset').onclick=()=>{events=[];loadScenario(selected);log('Scenario reset; prior application and acknowledgements cleared.');};
$('export').onclick=()=>{if(dirty)return;download('TrafficFlow-Agent-Report.json',JSON.stringify({createdAt:new Date().toISOString(),disclosure:'Deterministic educational simulation. No live sensors, trained perception model, external dispatch or real signal control.',analysis:result,simulation:applied,acknowledgedTeams:[...ack].map(i=>result.tasks[i].team),eventLog:events},null,2),'application/json');log('Exported the current simulation report.');};
loadScenario(selected);
})();
