(function(root){
'use strict';
const clone=x=>JSON.parse(JSON.stringify(x));
const clip=(x,a,b)=>Math.min(b,Math.max(a,x));
const base={scenario:'Routine flow',event:'none',camera:88,reports:0,age:10,demand:22,speed:48,rain:0,visibility:1500,lanes:3,blocked:0,pedestrians:12,emergency:false,authenticated:true,responder:true,green:58,walk:20,clearance:5,horizon:15};
const scenarios={
 routine:{name:'Routine flow',description:'Normal demand and no incident evidence.',input:{...base}},
 peak:{name:'Rush-hour queues',description:'A busy corridor needs a bounded signal timing adjustment.',input:{...base,scenario:'Rush-hour queues',event:'queue',camera:93,reports:4,demand:46,speed:17,pedestrians:24}},
 collision:{name:'Collision at J2',description:'Camera and vehicle reports agree; one lane is obstructed.',input:{...base,scenario:'Collision at J2',event:'collision',camera:94,reports:7,age:8,demand:38,speed:9,blocked:1,pedestrians:18}},
 ambulance:{name:'Emergency approach',description:'An authenticated V2X priority request reaches the corridor.',input:{...base,scenario:'Emergency approach',event:'queue',camera:90,reports:3,demand:35,speed:21,emergency:true,pedestrians:26}},
 storm:{name:'Heavy rain',description:'Low visibility reduces usable capacity and incident certainty.',input:{...base,scenario:'Heavy rain',event:'queue',camera:67,reports:3,demand:32,speed:24,rain:38,visibility:110,pedestrians:16}},
 conflict:{name:'Conflicting reports',description:'A weak camera event has no corroborating vehicle report.',input:{...base,scenario:'Conflicting reports',event:'collision',camera:42,reports:0,age:180,demand:31,speed:30,blocked:1,emergency:true,authenticated:false}},
 unsafe:{name:'Unsafe plan challenge',description:'Proposed timings violate demo guardrails. The validator must block them.',input:{...base,scenario:'Unsafe plan challenge',event:'collision',camera:96,reports:8,demand:43,speed:8,lanes:2,blocked:2,emergency:true,green:92,walk:5,clearance:1,pedestrians:35}}
};
const policy={minWalk:15,minClearance:4,maxGreen:65,cycle:120,minOtherGreen:25,maxAge:60,confirmation:70,emergencyVisibility:150};
const ranges={camera:[0,100],reports:[0,50],age:[0,600],demand:[0,80],speed:[0,100],rain:[0,100],visibility:[20,5000],lanes:[1,4],blocked:[0,4],pedestrians:[0,100],green:[10,100],walk:[5,45],clearance:[1,15],horizon:[5,30]};
function validate(s){if(!s||typeof s!=='object')throw Error('Scenario input is missing.');for(const [k,[lo,hi]] of Object.entries(ranges))if(typeof s[k]!=='number'||!Number.isFinite(s[k])||s[k]<lo||s[k]>hi)throw Error(k+' must be between '+lo+' and '+hi+'.');for(const k of ['lanes','blocked','reports','pedestrians','horizon'])if(!Number.isInteger(s[k]))throw Error(k+' must be a whole number.');if(s.blocked>s.lanes)throw Error('Blocked lanes cannot exceed total lanes.');if(!['none','queue','collision','debris'].includes(s.event))throw Error('Choose a supported camera event.');for(const k of ['emergency','authenticated','responder'])if(typeof s[k]!=='boolean')throw Error('Invalid '+k+' flag.');return s;}
function perceive(s){const fresh=s.age<=policy.maxAge;const event=s.event!=='none';const cameraWeight=s.visibility<150?.65:1;const raw=event?.55*s.camera*cameraWeight+(fresh?Math.min(s.reports,8)/8*30:0)+(s.speed<20?15:0):0;const score=Math.round(raw);const confirmed=event&&score>=policy.confirmation&&fresh&&s.reports>=2;const uncertain=event&&!confirmed;const label=confirmed?(s.event==='collision'?'Collision confirmed':s.event==='debris'?'Obstruction confirmed':'Queue confirmed'):uncertain?'Incident unverified':'No incident detected';return {fresh,score,confirmed,uncertain,label,cameraWeight,corroborated:s.reports>=2&&fresh,notes:[`${s.camera}% simulated camera confidence for ${s.event}.`,`${s.reports} V2X event reports; age ${s.age}s (${fresh?'fresh':'stale'}).`,s.visibility<150?'Low visibility discounts camera evidence by 35%.':'Visibility does not discount camera evidence.','Fusion score is a heuristic evidence score, not a calibrated probability.']};}
function initialQueues(s){return [Math.round(s.demand*.8),Math.round(s.demand*(s.blocked?1.5:1.0)),Math.round(s.demand*.55)];}
// Deterministic fluid queue model. One simulation step = one minute.
// Finite storage and backward supply limits keep internal flows from exceeding capacity.
function simulate(s,actions=[],minutes=s.horizon){validate(s);const active=new Set(actions.filter(a=>a.status==='approved').map(a=>a.type));const weather=Math.max(.42,1-s.rain*.006-(s.visibility<150?.18:0));const storage=[90,75,85],q=initialQueues(s).map((v,i)=>Math.min(v,storage[i]));const timeline=[];let cumulativeWait=0,overflow=0,throughput=0,peak=0;
 const timed=active.has('timing')||active.has('priority');const green=timed?s.green:42;const diverted=active.has('diversion')?.12:0;const monitoring=active.has('weather');const reduction=monitoring?.96:1;const clearanceAt=active.has('dispatch')&&active.has('isolate')?6:active.has('dispatch')?10:Infinity;
 for(let minute=0;minute<=minutes;minute++){
  peak=Math.max(peak,...q);timeline.push({minute,queues:q.map(x=>Math.round(x*10)/10),total:Math.round(q.reduce((a,b)=>a+b,0)*10)/10});if(minute===minutes)break;
  const blocked=minute>=clearanceAt?0:s.blocked;const effective=[s.lanes,Math.max(0,s.lanes-blocked),s.lanes];const capacities=effective.map((lanes,i)=>30*lanes*(i===1?green:42)/120*weather*reduction);
  const leaving=Math.min(q[2],capacities[2]);const transfer12=Math.min(q[1],capacities[1],storage[2]-q[2]+leaving);const transfer01=Math.min(q[0],capacities[0],storage[1]-q[1]+transfer12);const arriving=s.demand*(1-diverted);const accepted=Math.min(arriving,storage[0]-q[0]+transfer01);overflow+=arriving-accepted;
  q[0]+=accepted-transfer01;q[1]+=transfer01-transfer12;q[2]+=transfer12-leaving;
  cumulativeWait+=q.reduce((a,b)=>a+b,0);throughput+=leaving;
 }
 const last=timeline[timeline.length-1];return {timeline,finalQueues:last.queues,finalTotal:last.total,waitVehicleMinutes:Math.round(cumulativeWait),upstreamBacklog:Math.round(overflow),throughput:Math.round(throughput),peak:Math.round(peak),storage,spillover:timeline.some(t=>t.queues.some((v,i)=>v>=storage[i]*.85)),clearanceMinutes:Number.isFinite(clearanceAt)?clearanceAt:null};}
function plan(s,p,forecast){let actions=[];const add=(id,type,title,reason,owner)=>actions.push({id,type,title,reason,owner,status:'pending',checks:[]});
 if(p.uncertain)add('verify','verify','Request operator verification','Evidence does not meet the corroboration rule. Ask for a camera review before incident-specific changes.','Control-room operator');
 if(s.demand>28||forecast.spillover)add('timing','timing',`Set J2 main green to ${s.green}s`,`Projected demand is ${s.demand} vehicles/min. Retain ${s.walk}s pedestrian time and ${s.clearance}s clearance within a 120s cycle.`,'Signal-planning agent');
 if(p.confirmed&&['collision','debris'].includes(s.event)){add('dispatch','dispatch','Assign a simulated response team','Corroborated incident evidence supports an operator-approved response task.','Response coordinator');if(s.blocked>0)add('isolate','isolate',`Protect ${s.blocked} obstructed lane${s.blocked>1?'s':''} at J2`,'Protect the reported obstruction while retaining a passable lane.','Road response team');}
 if(s.emergency)add('priority','priority','Reserve a simulated emergency corridor','V2X priority request requires a valid sender, fresh reports and protected crossing time.','Emergency coordinator');
 if(forecast.spillover&&p.confirmed)add('diversion','diversion','Offer a 12% demand-diversion scenario','The model predicts queue spillover. Test voluntary diversion before issuing any real routing instruction.','Traffic operator');
 if(s.rain>=20||s.visibility<150)add('weather','weather','Issue a weather caution scenario','Rain or low visibility reduces modeled discharge capacity. Add an operator/public caution.','Safety agent');
 if(!actions.length)add('monitor','monitor','Maintain normal operation','No confirmed incident or demand trigger requires an intervention.','Control-room operator');
 return actions;}
function checkPlan(s,p,actions){return actions.map(a=>{const checks=[];const check=(name,pass,detail)=>checks.push({name,pass,detail});const traffic=['timing','priority'];
 if(traffic.includes(a.type)){check('Pedestrian protection',s.walk>=policy.minWalk,`Walk interval ${s.walk}s; demo minimum ${policy.minWalk}s.`);check('Clearance interval',s.clearance>=policy.minClearance,`Clearance ${s.clearance}s; demo minimum ${policy.minClearance}s.`);check('Maximum main green',s.green<=policy.maxGreen,`Requested ${s.green}s; demo cap ${policy.maxGreen}s.`);check('Other movements retained',policy.cycle-s.green-s.walk-s.clearance>=policy.minOtherGreen,`${policy.cycle-s.green-s.walk-s.clearance}s left for other movements; minimum ${policy.minOtherGreen}s.`);check('Fresh observations',p.fresh,`Observation age ${s.age}s; limit ${policy.maxAge}s.`);check('Passable road',s.blocked<s.lanes,`${s.lanes-s.blocked} usable lanes before any clearance.`);}
 if(['dispatch','isolate','diversion'].includes(a.type))check('Corroborated incident',p.confirmed,'Incident must pass the evidence rule.');
 if(['dispatch','isolate'].includes(a.type))check('Team available',s.responder,'A response team must be available in this simulation.');
 if(a.type==='isolate')check('At least one lane open',s.lanes-s.blocked>=1,`${s.lanes-s.blocked} lanes remain. A full closure requires a separate real-world procedure.`);
 if(a.type==='priority'){check('Authenticated V2X request',s.authenticated,'The simulated priority request must be authenticated.');check('Emergency visibility',s.visibility>=policy.emergencyVisibility,`Visibility ${s.visibility}m; demo minimum ${policy.emergencyVisibility}m.`);check('Team available',s.responder,'A simulated response team must be available.');}
 if(a.type==='diversion')check('Passable corridor',s.blocked<s.lanes,'Full blockage requires manual handling before a diversion scenario.');
 if(!checks.length)check('Advisory only',true,'This action does not change a signal or close a lane.');
 return {...a,checks,status:checks.every(c=>c.pass)?'approved':'blocked'};});}
function coordinate(s,p,actions){const approved=actions.filter(a=>a.status==='approved');const tasks=[];if(approved.some(a=>a.type==='dispatch'))tasks.push({team:'Road response team',task:'Review the J2 incident and stage clearance resources.',status:'Simulated assignment ready'});if(approved.some(a=>a.type==='priority'))tasks.push({team:'Emergency coordinator',task:'Review the approach and coordinate a protected corridor.',status:'Simulated assignment ready'});if(approved.some(a=>a.type==='isolate'))tasks.push({team:'Road protection crew',task:'Confirm the obstruction and prepare a protected work area.',status:'Simulated assignment ready'});if(p.uncertain||actions.some(a=>a.status==='blocked'))tasks.push({team:'Control-room operator',task:'Review uncertain evidence or blocked plan checks.',status:'Needs review'});if(!tasks.length)tasks.push({team:'Control-room operator',task:'Monitor the corridor and review approved advisories.',status:'Monitoring'});return tasks;}
function explain(s,p,baseline,actions){const approved=actions.filter(a=>a.status==='approved'),blocked=actions.filter(a=>a.status==='blocked');return {operator:`${p.label}. Evidence score ${p.score}/100 uses camera confidence, fresh V2X reports and observed speed. ${baseline.spillover?'The queue model projects spillover.':'The queue model does not project spillover within this horizon.'} ${approved.length} actions passed demo checks; ${blocked.length} were blocked. ${blocked.length?'Blocked actions cannot be applied. ':''}Review the evidence and assumptions before simulating the approved plan.`,public:`DRAFT FOR DEMO ONLY: ${p.confirmed?`Traffic disruption is reported near Junction 2 (${s.event}).`:p.uncertain?'A possible traffic disruption near Junction 2 is being checked.':'Traffic is being monitored along the demonstration corridor.'} ${s.rain>=20||s.visibility<150?'Rain or low visibility may slow travel. ':''}${baseline.spillover?'Allow extra journey time. ':''}${s.emergency?'Keep emergency access clear. ':''}Follow official local directions. No public message has been sent.`};}
function analyze(input){const s=clone(validate(input)),perception=perceive(s),baseline=simulate(s);const actions=checkPlan(s,perception,plan(s,perception,baseline));return {version:'2.0',input:s,policy:clone(policy),perception,baseline,actions,tasks:coordinate(s,perception,actions),explanation:explain(s,perception,baseline,actions),trace:[{agent:'Perception',text:`Fused camera, V2X, weather and signal inputs. ${perception.label}.`},{agent:'Prediction',text:`Projected ${baseline.finalTotal} queued vehicles and ${baseline.upstreamBacklog} outside the corridor after ${s.horizon} min.`},{agent:'Planning',text:`Proposed ${actions.length} intervention${actions.length===1?'':'s'} with reasons.`},{agent:'Safety validator',text:`${actions.filter(a=>a.status==='approved').length} passed; ${actions.filter(a=>a.status==='blocked').length} blocked by demo guardrails.`},{agent:'Coordination',text:`Prepared ${coordinate(s,perception,actions).length} simulated tasks. No external dispatch.`},{agent:'Explanation',text:'Prepared separate operator and public drafts. Nothing published.'}]};}
function apply(result){if(!result||result.version!=='2.0')throw Error('Analyze a scenario first.');const fresh=analyze(result.input);const approved=fresh.actions.filter(a=>a.status==='approved');return {after:simulate(fresh.input,approved),applied:approved.map(a=>a.id),blocked:fresh.actions.filter(a=>a.status==='blocked').map(a=>a.id)};}
const api={base,scenarios,policy,validate,perceive,simulate,analyze,apply};if(typeof module!=='undefined')module.exports=api;root.TrafficAgents=api;
})(typeof globalThis!=='undefined'?globalThis:this);
