(()=>{'use strict';const M=TrafficModel,$=id=>document.getElementById(id);const colors=['#37c59c','#dcc147','#f29a4b','#ef7383'],inks=['#15705a','#7e6710','#974818','#a32943'];let model=M.fit(M.synthetic()),source='simulated',latest=null;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge=(label,rank)=>'<span class="badge" style="--tint:'+colors[rank]+'22;--ink:'+inks[rank]+'">'+esc(label)+'</span>';
const descriptions=['Traffic is flowing with relatively low pressure.','Traffic is building, with some slowdown.','Dense traffic and slower movement indicate congestion.','Very slow traffic and heavy road use indicate severe congestion.'];
const recommendations=[['Continue monitoring vehicle flow and road occupancy.','Keep junctions clear and maintain normal signal operation.'],['Monitor approaching junctions for queues.','Where practical, shift non-essential trips outside the busier period.'],['Check verified navigation information before choosing an alternate route.','For traffic operators: review queue lengths and signal timing.','Consider delaying a non-essential trip until demand eases.'],['Avoid entering a heavily queued section when a verified alternative is available.','For traffic operators: inspect bottlenecks and coordinate junction management.','Keep emergency access clear and follow local traffic instructions.']];
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function read(){const input={};M.keys.forEach(k=>{if($(k).value.trim()==='')throw Error('Enter '+k+'.');input[k]=Number($(k).value);});M.minuteOf($('time').value);return {input:M.keys.reduce((a,k)=>(a[k]=input[k],a),{}),location:$('location').value,time:$('time').value,horizon:Number($('horizon').value)};}
function run(){try{const state=read();M.keys.forEach((k,j)=>{if(state.input[k]<0||state.input[k]>M.limits[j])throw Error('Check the '+k+' range.');});if(!model.rows.some(r=>r.location===state.location))throw Error('Choose a location in the dataset.');const prediction=M.predict(model,state.input),future=M.forecast(model,state.input,state.location,state.time,state.horizon);latest={...state,prediction,future,source};$('input-error').textContent='';renderResult();scatter();patterns();return latest;}catch(e){$('input-error').textContent=e.message;throw e;}}
function renderResult(){const {input,prediction:p,future:f,time,location,horizon}=latest;$('result').style.setProperty('--accent',colors[p.rank]);$('result-content').innerHTML='<div class="result-head"><div class="signal" aria-hidden="true">'+[3,2,0].map(n=>'<i class="lamp '+((p.rank===n||(p.rank===1&&n===2))?'active':'')+'"></i>').join('')+'</div><div><div class="eyebrow">Current congestion class</div><div class="level">'+p.label+'</div><p class="result-copy">'+descriptions[p.rank]+'</p></div></div><div class="result-metrics"><div><small>Average speed</small><strong>'+input.speed.toFixed(1)+' <span>km/h</span></strong></div><div><small>Road occupancy</small><strong>'+input.occupancy.toFixed(1)+' <span>%</span></strong></div><div><small>Cluster distance</small><strong>'+p.distance.toFixed(2)+'</strong><span>Scaled units · lower is closer</span></div></div>'+(p.unusual?'<div class="result-note">Unusual combination: this input lies outside the typical range of its assigned cluster. Treat this result cautiously.</div>':'')+'<div class="result-actions"><span class="sub">'+esc(location)+' · '+esc(time)+'</span><button class="btn" id="report">Save result</button></div><div id="stale" class="stale" hidden>Inputs changed. Select Predict congestion to update the result.</div>';
 $('report').onclick=()=>download('TrafficFlow-prediction.json',JSON.stringify({project:'Traffic Congestion Prediction and Prevention using K-Means',dataSource:source==='simulated'?'Simulated demo data':'User-provided CSV; not independently validated',...latest,model:{rows:model.rows.length,k:4,silhouette:model.silhouette},limitation:'Cluster assignment is not a calibrated probability. Future estimate is a historical-profile scenario, not a validated forecast.'},null,2),'application/json');
 $('forecast-content').innerHTML=f?'<div class="forecast"><div><div class="eyebrow" style="color:#678198">In '+horizon+' minutes · '+f.time+'</div><h3>'+ (f.rank>p.rank?'Congestion may increase':f.rank<p.rank?'Congestion may ease':'Similar congestion may continue')+'</h3><p class="hint">Estimated speed '+f.input.speed.toFixed(1)+' km/h · occupancy '+f.input.occupancy.toFixed(1)+'%</p></div>'+badge(f.label,f.rank)+'</div><p class="hint" style="margin-top:14px">'+(source==='simulated'?'Simulated time-pattern estimate.':'Estimate from the uploaded time patterns.')+' No live traffic feed.'+(f.unusual?' Projected conditions are unusual for the assigned cluster.':'')+'</p>':'<p class="hint">Not enough observations near these times at this location to estimate ahead. The current congestion classification is still available.</p>';
 const rank=Math.max(p.rank,f?.rank??0);$('actions').replaceChildren(...recommendations[rank].map(t=>{const li=document.createElement('li');li.textContent=t;return li;}));}
function scatter(){const w=580,h=240,left=44,right=560,top=15,bottom=202;let s='<svg class="chart" viewBox="0 0 '+w+' '+h+'" role="img" aria-label="Training observations grouped by congestion level, plotted by traffic density and speed">';const x=v=>left+v/200*(right-left),y=v=>bottom-v/100*(bottom-top);for(let v=0;v<=100;v+=25)s+='<line x1="'+left+'" y1="'+y(v)+'" x2="'+right+'" y2="'+y(v)+'" stroke="#e8edf3"/><text x="32" y="'+(y(v)+4)+'" text-anchor="end" fill="#6e8095" font-size="11">'+v+'</text>';for(let v=0;v<=200;v+=50)s+='<text x="'+x(v)+'" y="220" text-anchor="middle" fill="#6e8095" font-size="11">'+v+'</text>';
 const stride=Math.max(1,Math.floor(model.rows.length/200));for(let i=0;i<model.rows.length;i+=stride){const r=model.rows[i],rank=model.order.indexOf(model.assignment[i]);s+='<circle cx="'+x(r.density)+'" cy="'+y(r.speed)+'" r="3" fill="'+colors[rank]+'" opacity=".6"/>';}
 if(latest){const r=latest.input;s+='<circle cx="'+x(r.density)+'" cy="'+y(r.speed)+'" r="8" fill="white" stroke="#152b44" stroke-width="2.5"/><circle cx="'+x(r.density)+'" cy="'+y(r.speed)+'" r="3" fill="#152b44"/>';}
 s+='<text x="45" y="12" fill="#657b92" font-size="11">Speed (km/h)</text><text x="'+right+'" y="239" fill="#657b92" font-size="11" text-anchor="end">Density (vehicles/km)</text></svg>';$('scatter').innerHTML=s;}
function patterns(){const location=latest?.location||$('location').value;const rows=model.rows.filter(r=>r.location===location);const hourly=Array.from({length:24},(_,h)=>{const rr=rows.filter(r=>Math.floor(M.minuteOf(r.time)/60)===h);return rr.length?rr.reduce((a,r)=>a+M.predict(model,r).rank,0)/rr.length:null;});const present=hourly.map((v,h)=>({v,h})).filter(x=>x.v!==null).sort((a,b)=>b.v-a.v);$('pattern-caption').textContent=location+' · '+(present.length?'Highest mean congestion near '+String(present[0].h).padStart(2,'0')+':00':'No hourly history');let s='<svg class="chart" viewBox="0 0 440 115" role="img" aria-label="Average congestion rank by hour for selected location">';hourly.forEach((v,h)=>{if(v!==null)s+='<rect x="'+(8+h*18)+'" y="'+(83-v*22)+'" width="11" height="'+Math.max(3,v*22)+'" rx="3" fill="'+colors[Math.round(v)]+'"/>';if(h%6===0)s+='<text x="'+(8+h*18)+'" y="106" font-size="11" fill="#647b92">'+String(h).padStart(2,'0')+':00</text>';});s+='</svg>';$('hourly').innerHTML=s;const groups=[...new Set(model.rows.map(r=>r.location))].map(name=>{const ids=model.rows.map((r,i)=>r.location===name?i:-1).filter(i=>i>=0);return {name,pct:100*ids.filter(i=>model.order.indexOf(model.assignment[i])>=2).length/ids.length};}).sort((a,b)=>b.pct-a.pct);$('hotspots').innerHTML=groups.slice(0,5).map(g=>'<div class="roadrow"><span>'+esc(g.name)+'</span><div class="bar"><div style="width:'+g.pct+'%"></div></div><span>'+g.pct.toFixed(0)+'%</span></div>').join('');}
function modelUI(){const chosen=$('location').value;const names=[...new Set(model.rows.map(r=>r.location))];$('location').replaceChildren(...names.map(n=>{const o=document.createElement('option');o.value=n;o.textContent=n;return o;}));if(names.includes(chosen))$('location').value=chosen;$('source').textContent=source==='simulated'?'Demo model · 2,016 simulated observations':'Custom model · '+model.rows.length.toLocaleString()+' uploaded observations';$('pattern-source').textContent=source==='simulated'?'Simulated history':'Uploaded data';$('stats').innerHTML='<div><strong>'+model.rows.length.toLocaleString()+'</strong><small>Training observations</small></div><div><strong>'+model.silhouette.toFixed(3)+'</strong><small>Sample silhouette</small></div><div><strong>'+model.iterations+'</strong><small>Iterations · best run</small></div>';$('centroids').innerHTML=model.order.map((c,rank)=>'<tr><td>'+M.labels[rank]+'</td>'+model.rawCenters[c].map(v=>'<td>'+v.toFixed(1)+'</td>').join('')+'</tr>').join('');}
M.labels.forEach((label,i)=>{const b=document.createElement('button');b.type='button';b.className='preset';b.textContent=label;b.onclick=()=>{M.keys.forEach((k,j)=>$(k).value=M.prototypes[i][j]);$('time').value=['06:00','12:00','17:00','18:00'][i];try{run();}catch{}};$('presets').append(b);});$('legend').innerHTML=M.labels.map((l,i)=>'<span><i style="background:'+colors[i]+'"></i>'+l+'</span>').join('')+'<span>◉ Your input</span>';
$('predict-form').addEventListener('submit',e=>{e.preventDefault();try{run();}catch{}});$('predict-form').addEventListener('input',()=>{if($('stale'))$('stale').hidden=false;});$('predict-form').addEventListener('change',()=>{if($('stale'))$('stale').hidden=false;});
$('sample').onclick=()=>download('trafficflow-simulated-sample.csv',M.toCSV(M.synthetic()),'text/csv;charset=utf-8');
$('reset').onclick=()=>{model=M.fit(M.synthetic());source='simulated';modelUI();$('csv').value='';$('upload-status').textContent='Demo model restored.';try{run();}catch{}};
$('csv').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;const status=$('upload-status');try{if(f.size>2*1024*1024)throw Error('Please use a CSV under 2 MB.');status.textContent='Validating data and training the model…';const text=await f.text();await new Promise(r=>setTimeout(r,30));const rows=M.parseCSV(text);const candidate=M.fit(rows);model=candidate;source='uploaded';modelUI();status.textContent='Trained successfully on '+rows.length+' observations. Model stays in this tab.';try{run();}catch{}}catch(err){status.textContent=err.message+' Previous model retained.';}finally{e.target.value='';}});
modelUI();run();
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();const tool={name:'predict_traffic_congestion',title:'Predict traffic congestion',description:'Set the visible traffic inputs and run the current K-Means model. Results are academic demo classifications, not live traffic advice.',inputSchema:{type:'object',properties:{vehicles:{type:'integer',minimum:0,maximum:600},speed:{type:'number',minimum:0,maximum:100},density:{type:'number',minimum:0,maximum:200},occupancy:{type:'number',minimum:0,maximum:100},location:{type:'string'},time:{type:'string'},horizon:{type:'integer',enum:[15,30,60]}},required:[...M.keys,'location','time','horizon'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{M.predict(model,input);M.minuteOf(input.time);if(![15,30,60].includes(input.horizon)||!model.rows.some(r=>r.location===input.location))throw Error('Invalid location or horizon.');[...M.keys,'location','time','horizon'].forEach(k=>$(k).value=input[k]);const result=run();return {level:result.prediction.label,future:result.future?.label??null,source};}};try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
})();
